/* 
 * Bitcoind
 *
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// BipReject : the BIP rejection status

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct BipReject {
  /// if the BIP is rejected
  #[serde(rename = "status")]
  status: Option<bool>
}

impl BipReject {
  /// the BIP rejection status
  pub fn new() -> BipReject {
    BipReject {
      status: None
    }
  }

  pub fn set_status(&mut self, status: bool) {
    self.status = Some(status);
  }

  pub fn with_status(mut self, status: bool) -> BipReject {
    self.status = Some(status);
    self
  }

  pub fn status(&self) -> Option<&bool> {
    self.status.as_ref()
  }

  pub fn reset_status(&mut self) {
    self.status = None;
  }

}



