/* 
 * Bitcoind
 *
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

/// ChainInfoBip9Softforks : status of BIP9 softforks in progress

#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChainInfoBip9Softforks {
  #[serde(rename = "name")]
  name: Option<::models::Bip9>
}

impl ChainInfoBip9Softforks {
  /// status of BIP9 softforks in progress
  pub fn new() -> ChainInfoBip9Softforks {
    ChainInfoBip9Softforks {
      name: None
    }
  }

  pub fn set_name(&mut self, name: ::models::Bip9) {
    self.name = Some(name);
  }

  pub fn with_name(mut self, name: ::models::Bip9) -> ChainInfoBip9Softforks {
    self.name = Some(name);
    self
  }

  pub fn name(&self) -> Option<&::models::Bip9> {
    self.name.as_ref()
  }

  pub fn reset_name(&mut self) {
    self.name = None;
  }

}



