/* 
 * Bitcoind
 *
 * The REST API can be enabled with the `-rest` option. The interface runs on the same port as the JSON-RPC interface, by default port `8332` for **mainnet**, port `18332` for **testnet**, and port `18443` for **regtest**.
 *
 * OpenAPI spec version: 0.16
 * Contact: johan@lepetitbloc.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponseDefault {
  #[serde(rename = "txid")]
  txid: Option<::models::Transaction>
}

impl InlineResponseDefault {
  pub fn new() -> InlineResponseDefault {
    InlineResponseDefault {
      txid: None
    }
  }

  pub fn set_txid(&mut self, txid: ::models::Transaction) {
    self.txid = Some(txid);
  }

  pub fn with_txid(mut self, txid: ::models::Transaction) -> InlineResponseDefault {
    self.txid = Some(txid);
    self
  }

  pub fn txid(&self) -> Option<&::models::Transaction> {
    self.txid.as_ref()
  }

  pub fn reset_txid(&mut self) {
    self.txid = None;
  }

}



